kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovs-flows-config-publisher
  namespace: openshift-network-operator
  annotations:
    openshift.io/description: "Can create and update the ovs-flows-config ConfigMap values"
rules:
  - apiGroups: [ "" ]
    resources:
      - configmaps
    resourceNames:
      - ovs-flows-config
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovs-flows-config-subscriber
  namespace: openshift-network-operator
  annotations:
    openshift.io/description: "Can read and watch the ovs-flows-config ConfigMap values"
rules:
  - apiGroups: [ "" ]
    resources:
      - configmaps
    resourceNames:
      - ovs-flows-config
    verbs:
      - get
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ovs-flows-config-subscriber
  namespace: openshift-network-operator
  annotations:
    openshift.io/description: "Grants read access to the ovs-flows-config ConfigMap values"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-network-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ovs-flows-config-subscriber